In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import geopandas as gpd

nychares_raw_path = '/content/drive/MyDrive/Informatics Final Project/Data_Sources/raw_data/NYCHA_Residential_Addresses_20260314.csv'

nychares = pd.read_csv(nychares_raw_path)

nychares.head()

,DEVELOPMENT,TDS #,BUILDING #,STAIRHALL#,BOROUGH,HOUSE #,STREET,ADDRESS,CITY,STATE,...,NEIGHBORHOOD TABULATION AREA CODE,NEIGHBORHOOD TABULATION AREA NAME,COMMUNITY DISTRICT,CITY COUNCIL DISTRICT,STATE ASSEMBLY DISTRICT,STATE SENATE DISTRICT,US CONGRESSIONAL DISTRICT,PRIVATELY MANAGED,LATITUDE,LONGITUDE
0,1162-1176 WASHINGTON AVENUE,233,1,3,BRONX,1162,WASHINGTON AVENUE,1162 WASHINGTON AVENUE,BRONX,NY,...,BX0302,Claremont Village-Claremont (East),3,16,79,32,15,NaN,40.829928,-73.907535
1,1471 WATSON AVENUE,214,1,29,BRONX,1471,WATSON AVENUE,1471 WATSON AVENUE,BRONX,NY,...,BX0901,Soundview-Bruckner-Bronx River,9,17,85,32,14,NaN,40.825850,-73.880943
2,154 WEST 84TH STREET,359,1,47,MANHATTAN,154,WEST 84TH STREET,154 WEST 84TH STREET,NEW YORK,NY,...,MN0702,Upper West Side (Central),7,6,69,47,12,YES,40.785976,-73.975263
3,303 VERNON AVENUE,156,1,25,BROOKLYN,303,VERNON AVENUE,303 VERNON AVENUE,BROOKLYN,NY,...,BK0302,Bedford-Stuyvesant (East),3,36,56,25,8,NaN,40.695921,-73.939715
4,45 ALLEN STREET,265,1,3,MANHATTAN,45,ALLEN STREET,45 ALLEN STREET,NEW YORK,NY,...,MN0301,Chinatown-Two Bridges,3,1,65,27,10,NaN,40.716665,-73.992152

In [ ]:
nychares_gdf = gpd.GeoDataFrame(
  nychares,
  geometry = gpd.points_from_xy(nychares['LONGITUDE'], nychares['LATITUDE'], crs="EPSG:2263"))

nychares_gdf.head()

,DEVELOPMENT,TDS #,BUILDING #,STAIRHALL#,BOROUGH,HOUSE #,STREET,ADDRESS,CITY,STATE,...,NEIGHBORHOOD TABULATION AREA NAME,COMMUNITY DISTRICT,CITY COUNCIL DISTRICT,STATE ASSEMBLY DISTRICT,STATE SENATE DISTRICT,US CONGRESSIONAL DISTRICT,PRIVATELY MANAGED,LATITUDE,LONGITUDE,geometry
0,1162-1176 WASHINGTON AVENUE,233,1,3,BRONX,1162,WASHINGTON AVENUE,1162 WASHINGTON AVENUE,BRONX,NY,...,Claremont Village-Claremont (East),3,16,79,32,15,NaN,40.829928,-73.907535,POINT (-73.908 40.83)
1,1471 WATSON AVENUE,214,1,29,BRONX,1471,WATSON AVENUE,1471 WATSON AVENUE,BRONX,NY,...,Soundview-Bruckner-Bronx River,9,17,85,32,14,NaN,40.825850,-73.880943,POINT (-73.881 40.826)
2,154 WEST 84TH STREET,359,1,47,MANHATTAN,154,WEST 84TH STREET,154 WEST 84TH STREET,NEW YORK,NY,...,Upper West Side (Central),7,6,69,47,12,YES,40.785976,-73.975263,POINT (-73.975 40.786)
3,303 VERNON AVENUE,156,1,25,BROOKLYN,303,VERNON AVENUE,303 VERNON AVENUE,BROOKLYN,NY,...,Bedford-Stuyvesant (East),3,36,56,25,8,NaN,40.695921,-73.939715,POINT (-73.94 40.696)
4,45 ALLEN STREET,265,1,3,MANHATTAN,45,ALLEN STREET,45 ALLEN STREET,NEW YORK,NY,...,Chinatown-Two Bridges,3,1,65,27,10,NaN,40.716665,-73.992152,POINT (-73.992 40.717)

In [ ]:
cleaned_nyres_gdf = nychares_gdf.copy()

# Standardize column names
cleaned_nyres_gdf.columns= (cleaned_nyres_gdf.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_"))


cleaned_nyres_gdf.head()

,development,tds_#,building_#,stairhall#,borough,house_#,street,address,city,state,...,neighborhood_tabulation_area_name,community_district,city_council_district,state_assembly_district,state_senate_district,us_congressional_district,privately_managed,latitude,longitude,geometry
0,1162-1176 WASHINGTON AVENUE,233,1,3,BRONX,1162,WASHINGTON AVENUE,1162 WASHINGTON AVENUE,BRONX,NY,...,Claremont Village-Claremont (East),3,16,79,32,15,NaN,40.829928,-73.907535,POINT (-73.908 40.83)
1,1471 WATSON AVENUE,214,1,29,BRONX,1471,WATSON AVENUE,1471 WATSON AVENUE,BRONX,NY,...,Soundview-Bruckner-Bronx River,9,17,85,32,14,NaN,40.825850,-73.880943,POINT (-73.881 40.826)
2,154 WEST 84TH STREET,359,1,47,MANHATTAN,154,WEST 84TH STREET,154 WEST 84TH STREET,NEW YORK,NY,...,Upper West Side (Central),7,6,69,47,12,YES,40.785976,-73.975263,POINT (-73.975 40.786)
3,303 VERNON AVENUE,156,1,25,BROOKLYN,303,VERNON AVENUE,303 VERNON AVENUE,BROOKLYN,NY,...,Bedford-Stuyvesant (East),3,36,56,25,8,NaN,40.695921,-73.939715,POINT (-73.94 40.696)
4,45 ALLEN STREET,265,1,3,MANHATTAN,45,ALLEN STREET,45 ALLEN STREET,NEW YORK,NY,...,Chinatown-Two Bridges,3,1,65,27,10,NaN,40.716665,-73.992152,POINT (-73.992 40.717)

In [ ]:
cleaned_nyres_gdf.to_csv('/content/drive/MyDrive/Informatics Final Project/Data_Sources/raw_data/nycha_residential.csv', index = False)