In [3]:
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import seaborn as sns

nycha_dev_data_raw_path = '../data/raw/NYCHA_Development_Data_Book_20260314.csv'
nycha_dev_data = pd.read_csv(nycha_dev_data_raw_path)

nycha_dev_data.info()
nycha_dev_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 52 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DATA AS OF                                 346 non-null    object
 1   DEVELOPMENT                                346 non-null    object
 2   HUD AMP#                                   343 non-null    object
 3   TDS#                                       344 non-null    object
 4   CONSOLIDATED TDS#                          340 non-null    object
 5   DEVELOPMENT EDP#                           339 non-null    object
 6   OPERATING EDP#                             339 non-null    object
 7   HUD #                                      340 non-null    object
 8   PROGRAM                                    346 non-null    object
 9   METHOD                                     343 non-null    object
 10  TYPE                                       346 non-null    object
 11  NUMBER OF SECTION 8 TRANSITION APARTMENTS  259 non-null    float64
 12  NUMBER OF CURRENT APARTMENTS               344 non-null    object
 13  TOTAL NUMBER OF APARTMENTS                 344 non-null    object
 14  NUMBER OF RENTAL ROOMS                     340 non-null    object
 15  AVG NO R/R PER APARTMENT                   340 non-null    float64
 16  POPULATION SECTION 8 TRANSITION            309 non-null    object
 17  POPULATION PUBLIC HOUSING                  305 non-null    object
 18  TOTAL POPULATION                           338 non-null    object
 19  TOTAL # OF FIXED INCOME HOUSEHOLD          305 non-null    object
 20  PERCENT FIXED INCOME HOUSEHOLDS            305 non-null    float64
 21  NUMBER OF RESIDENTIAL BLDGS                344 non-null    float64
 22  NUMBER OF NON-RESIDENTIAL BLDGS            341 non-null    float64
 23  NUMBER OF STAIRHALLS                       343 non-null    float64
 24  NUMBER OF STORIES                          344 non-null    object
 25  TOTAL AREA SQ FT                           338 non-null    object
 26  ACRES                                      338 non-null    float64
 27  NET DEV AREA SQ FT                         344 non-null    object
 28  EXCLUDING PARK ACRES                       344 non-null    float64
 29  BLDG COVERAGE SQ FT                        329 non-null    object
 30  CUBAGE CU FT                               328 non-null    object
 31  BLDG COVERAGE %                            329 non-null    object
 32  DENSITY                                    338 non-null    float64
 33  DEVELOPMENT COST                           333 non-null    object
 34  PER RENTAL ROOM                            332 non-null    object
 35  AVG MONTHLY GROSS RENT                     338 non-null    object
 36  LOCATION STREET A                          346 non-null    object
 37  LOCATION STREET B                          341 non-null    object
 38  LOCATION STREET C                          322 non-null    object
 39  LOCATION STREET D                          271 non-null    object
 40  BOROUGH                                    346 non-null    object
 41  COMMUNITY DISTIRCT                         336 non-null    object
 42  US CONGRESSIONAL DISTRICT                  346 non-null    object
 43  NY STATE SENATE DISTRICT                   346 non-null    object
 44  NY STATE ASSEMBLY DISTRICT                 346 non-null    object
 45  NY CITY COUNCIL DISTRICT                   346 non-null    object
 46  COMPLETION DATE                            340 non-null    object
 47  FEDERALIZED DEVELOPMENT                    66 non-null     object
 48  SENIOR DEVELOPMENT                         55 non-null     object
 49  ELECTRICITY PAID BY RESIDENTS              91 non-null     object
 50  PRIVATE MANAGEMENT                         33 non-null     object
 51  RAD TRANSFERRED DATE                       101 non-null    object
dtypes: float64(9), object(43)
memory usage: 140.7+ KB

,DATA AS OF,DEVELOPMENT,HUD AMP#,TDS#,CONSOLIDATED TDS#,DEVELOPMENT EDP#,OPERATING EDP#,HUD #,PROGRAM,METHOD,...,US CONGRESSIONAL DISTRICT,NY STATE SENATE DISTRICT,NY STATE ASSEMBLY DISTRICT,NY CITY COUNCIL DISTRICT,COMPLETION DATE,FEDERALIZED DEVELOPMENT,SENIOR DEVELOPMENT,ELECTRICITY PAID BY RESIDENTS,PRIVATE MANAGEMENT,RAD TRANSFERRED DATE
0,1/1/2025,1010 EAST 178TH STREET,NY005011330,180,180,289,289,NY005090,FEDERAL,CONVENTIONAL,...,15,32,87,15,1971-03-31T00:00:00.000,NaN,NaN,NaN,NaN,06/24/2025
1,1/1/2025,104-14 TAPSCOTT STREET,NY005011670,242,167,361,283,NY005174,FEDERAL,TURNKEY,...,09,25,55,41,1972-10-31T00:00:00.000,NaN,NaN,NaN,NaN,11/28/2023
2,1/1/2025,1162-1176 WASHINGTON AVENUE,NY005013080,233,308,354,344,NY005138,FEDERAL,TURNKEY,...,15,32,79,16,1975-12-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN
3,1/1/2025,131 SAINT NICHOLAS AVENUE,NY005010970,154,097,264,261,NY005065,FEDERAL,CONVENTIONAL,...,13,30,70,09,1965-03-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN
4,1/1/2025,1471 WATSON AVENUE,NY005010670,214,067,332,222,NY005162,FEDERAL,TURNKEY,...,14,32,85,17,1970-12-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN

In [4]:
num_unique_values = nycha_dev_data['DATA AS OF'].nunique()
print(f"Number of unique values in 'DATA AS OF' column: {num_unique_values}")

Number of unique values in 'DATA AS OF' column: 1

In [5]:
nycha_dev_data_clean = nycha_dev_data.drop(columns=['OPERATING EDP#','DEVELOPMENT EDP#','HUD AMP#','AVG NO R/R PER APARTMENT','POPULATION SECTION 8 TRANSITION','TOTAL # OF FIXED INCOME HOUSEHOLD','NUMBER OF NON-RESIDENTIAL BLDGS','NUMBER OF STAIRHALLS','NET DEV AREA SQ FT','ACRES','EXCLUDING PARK ACRES','CUBAGE CU FT','BLDG COVERAGE %','PER RENTAL ROOM','LOCATION STREET A','LOCATION STREET B','LOCATION STREET C','LOCATION STREET D','COMMUNITY DISTIRCT','US CONGRESSIONAL DISTRICT','NY STATE SENATE DISTRICT','NY STATE ASSEMBLY DISTRICT','NY CITY COUNCIL DISTRICT'])

In [10]:
nycha_dev_data_clean.columns = (nycha_dev_data_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace('#',""))


##nycha_dev_data_clean.head(15,)
nycha_dev_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 29 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   data_as_of                                 346 non-null    object
 1   development                                346 non-null    object
 2   tds                                        344 non-null    object
 3   consolidated_tds                           340 non-null    object
 4   hud_                                       340 non-null    object
 5   program                                    346 non-null    object
 6   method                                     343 non-null    object
 7   type                                       346 non-null    object
 8   number_of_section_8_transition_apartments  259 non-null    float64
 9   number_of_current_apartments               344 non-null    object
 10  total_number_of_apartments                 344 non-null    object
 11  number_of_rental_rooms                     340 non-null    object
 12  population_public_housing                  305 non-null    object
 13  total_population                           338 non-null    object
 14  percent_fixed_income_households            305 non-null    float64
 15  number_of_residential_bldgs                344 non-null    float64
 16  number_of_stories                          344 non-null    object
 17  total_area_sq_ft                           338 non-null    object
 18  bldg_coverage_sq_ft                        329 non-null    object
 19  density                                    338 non-null    float64
 20  development_cost                           333 non-null    object
 21  avg_monthly_gross_rent                     338 non-null    object
 22  borough                                    346 non-null    object
 23  completion_date                            340 non-null    datetime64[ns]
 24  federalized_development                    66 non-null     datetime64[ns]
 25  senior_development                         55 non-null     object
 26  electricity_paid_by_residents              91 non-null     object
 27  private_management                         33 non-null     object
 28  rad_transferred_date                       101 non-null    datetime64[ns]
dtypes: datetime64[ns](3), float64(4), object(22)
memory usage: 78.5+ KB

In [14]:
import pandas as pd

nycha_dev_data_clean['federalized_development'] = pd.to_datetime(
    nycha_dev_data_clean['federalized_development'],
    errors='coerce'
)

nycha_dev_data_clean['completion_date'] = pd.to_datetime(
    nycha_dev_data_clean['completion_date',
    errors='coerce'
)

In [16]:
nycha_dev_data_clean['rad_transferred_date'] = pd.to_datetime(
    nycha_dev_data_clean['rad_transferred_date'],
    errors='coerce'
)

In [17]:
nycha_dev_data_clean.head()

,data_as_of,development,tds,consolidated_tds,hud_,program,method,type,number_of_section_8_transition_apartments,number_of_current_apartments,...,density,development_cost,avg_monthly_gross_rent,borough,completion_date,federalized_development,senior_development,electricity_paid_by_residents,private_management,rad_transferred_date
0,1/1/2025,1010 EAST 178TH STREET,180,180,NY005090,FEDERAL,CONVENTIONAL,NEW CONST,0.0,218,...,197.0,"$5,031,405",$513,BRONX,1971-03-31,NaT,NaN,NaN,NaN,2025-06-24
1,1/1/2025,104-14 TAPSCOTT STREET,242,167,NY005174,FEDERAL,TURNKEY,NEW CONST,NaN,28,...,236.0,"$839,110",$604,BROOKLYN,1972-10-31,NaT,NaN,NaN,NaN,2023-11-28
2,1/1/2025,1162-1176 WASHINGTON AVENUE,233,308,NY005138,FEDERAL,TURNKEY,REHAB,0.0,64,...,292.0,"$2,205,187",$619,BRONX,1975-12-31,NaT,NaN,NaN,NaN,NaT
3,1/1/2025,131 SAINT NICHOLAS AVENUE,154,097,NY005065,FEDERAL,CONVENTIONAL,NEW CONST,0.0,98,...,207.0,"$1,880,013",$630,MANHATTAN,1965-03-31,NaT,NaN,NaN,NaN,NaT
4,1/1/2025,1471 WATSON AVENUE,214,067,NY005162,FEDERAL,TURNKEY,NEW CONST,0.0,95,...,124.0,"$2,278,928",$549,BRONX,1970-12-31,NaT,NaN,NaN,NaN,NaT

In [19]:
nycha_dev_data_clean.to_csv('../data/processed/cleaned_nycha.csv', index=False)